version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=nest_user
      - POSTGRES_PASSWORD=nest_pass
      - POSTGRES_DB=invest_gold_gjokaj
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3001:3000'
      
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_pass
      POSTGRES_DB: invest_gold_gjokaj
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nest_user -d invest_gold_gjokaj"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: