version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=nest_user
      - POSTGRES_PASSWORD=nest_pass
      - POSTGRES_DB=invest_gold_gjokaj
      - JWT_SECRET=hellothere123
      - EMAIL_USER=investgoldgjokaj2017@gmail.com
      - EMAIL_APP_PASSWORD=ayex zlbf qqjz jtkw
      - BANKART_API_KEY=260291IP026291-SIM
      - BANKART_SHARED_SECRET=ec436ec75011c59f16c8c8825675610f3a9c391879374f09d0
      - BANKART_API_URL=https://gateway.bankart.si/api/v3
      - BANKART_API_USERNAME=API0260291INVESTGOLDSHPK
      - BANKART_API_PASSWORD=TungjaTjetaa123.
      - SENDGRID_API_KEY=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
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3001:3000'
      
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_pass
      POSTGRES_DB: invest_gold_gjokaj
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nest_user -d invest_gold_gjokaj"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: